// Canvas Types
export const UPDATE_CANVAS = "UPDATE_CANVAS";
export const RESET_CANVAS = "RESET_CANVAS";
export const UPDATE_CANVAS_ZOOM = "UPDATE_CANVAS_ZOOM";
export const UPDATE_PRESET = "UPDATE_PRESET";
export const UPDATE_WIDTH = "UPDATE_WIDTH";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const UPDATE_BACKGROUND = "UPDATE_BACKGROUND";
export const UPDATE_BACKGROUND_IMAGE = "UPDATE_BACKGROUND_IMAGE";
export const UPDATE_BACKGROUND_OPACITY = "UPDATE_BACKGROUND_OPACITY";

// Right Pane
export const SET_ACTIVE_PANE = "SET_ACTIVE_PANE";

// Layers
export const ADD_LAYER_ITEM = "ADD_LAYER_ITEM";
export const RESET_LAYERS = "RESET_LAYERS";
export const UPDATE_SELECTED_ITEM_ID = "UPDATE_SELECTED_ITEM_ID";
export const UPDATE_ITEM_POSITION_BY_INDEX = "UPDATE_ITEM_POSITION_BY_INDEX";
export const UPDATE_ITEM_ANGLE_BY_INDEX = "UPDATE_ITEM_ANGLE_BY_INDEX";
export const UPDATE_DEVICE_SCREEN_FIT_BY_INDEX =
  "UPDATE_DEVICE_SCREEN_FIT_BY_INDEX";
export const UPDATE_LAYER_DEVICE_SCREEN_SOURCE =
  "UPDATE_LAYER_DEVICE_SCREEN_SOURCE";
export const REMOVE_LAYER_ITEM = "REMOVE_LAYER_ITEM";
export const MOVE_LAYER_ITEM = "MOVE_LAYER_ITEM";
export const UPDATE_LAYER_ITEM = "UPDATE_LAYER_ITEM";
export const DELETE_ITEMS_BY_IDS = "DELETE_ITEMS_BY_IDS";
