// Canvas Types
export const UPDATE_CANVAS = "UPDATE_CANVAS";
export const UPDATE_WIDTH = "UPDATE_WIDTH";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const UPDATE_BACKGROUND = "UPDATE_BACKGROUND";

// Right Pane
export const SET_ACTIVE_PANE = "SET_ACTIVE_PANE";

// Layers
export const ADD_LAYER_ITEM = "ADD_LAYER_ITEM";
export const UPDATE_LAYER_DEVICE_SCREEN_SOURCE =
  "UPDATE_LAYER_DEVICE_SCREEN_SOURCE";
export const REMOVE_LAYER_ITEM = "REMOVE_LAYER_ITEM";
export const MOVE_LAYER_ITEM = "MOVE_LAYER_ITEM";
