// Canvas Types
export const UPDATE_CANVAS = "UPDATE_CANVAS";
export const UPDATE_WIDTH = "UPDATE_WIDTH";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const UPDATE_BACKGROUND = "UPDATE_BACKGROUND";
